# Generated by Django 4.2.30 on 2026-04-20 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vault categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VaultEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('account_identifier', models.CharField(help_text='Email, username, phone or account alias.', max_length=180)),
                ('encrypted_secret', models.TextField(help_text='Encrypted credential payload (password/notes/etc).')),
                ('website_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='miProyecto.vaultcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('is_weak', models.BooleanField(default=False)),
                ('is_reused', models.BooleanField(default=False)),
                ('reused_count', models.PositiveIntegerField(default=0)),
                ('breached', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='miProyecto.vaultentry')),
            ],
            options={
                'verbose_name': 'Password health',
                'verbose_name_plural': 'Password health',
            },
        ),
        migrations.AddIndex(
            model_name='vaultentry',
            index=models.Index(fields=['user', 'title'], name='miProyecto__user_id_74108f_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultentry',
            index=models.Index(fields=['user', 'account_identifier'], name='miProyecto__user_id_c548bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vaultcategory',
            unique_together={('user', 'name')},
        ),
    ]
